// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
typedef void (*UniffiForeignFutureDroppedCallback)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
typedef uint64_t (*UniffiCallbackInterfaceClone)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
typedef struct UniffiForeignFutureDroppedCallbackStruct {
    uint64_t handle;
    UniffiForeignFutureDroppedCallback _Nonnull free;
} UniffiForeignFutureDroppedCallbackStruct;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
typedef struct UniffiForeignFutureResultU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureResultU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
typedef struct UniffiForeignFutureResultI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureResultI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
typedef struct UniffiForeignFutureResultU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureResultU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
typedef struct UniffiForeignFutureResultI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureResultI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
typedef struct UniffiForeignFutureResultU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureResultU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
typedef struct UniffiForeignFutureResultI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureResultI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
typedef struct UniffiForeignFutureResultU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureResultU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
typedef struct UniffiForeignFutureResultI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureResultI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
typedef struct UniffiForeignFutureResultF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureResultF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
typedef struct UniffiForeignFutureResultF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureResultF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
typedef struct UniffiForeignFutureResultRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureResultRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
typedef struct UniffiForeignFutureResultVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureResultVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureResultVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_TOKEN_STATS_HOST_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_TOKEN_STATS_HOST_METHOD0
typedef void (*UniffiCallbackInterfaceTokenStatsHostMethod0)(uint64_t, int64_t, int32_t* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_TOKEN_STATS_HOST_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_TOKEN_STATS_HOST_METHOD1
typedef void (*UniffiCallbackInterfaceTokenStatsHostMethod1)(uint64_t, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_TOKEN_STATS_HOST_METHOD2
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_TOKEN_STATS_HOST_METHOD2
typedef void (*UniffiCallbackInterfaceTokenStatsHostMethod2)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_TOKEN_STATS_HOST
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_TOKEN_STATS_HOST
typedef struct UniffiVTableCallbackInterfaceTokenStatsHost {
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
    UniffiCallbackInterfaceClone _Nonnull uniffiClone;
    UniffiCallbackInterfaceTokenStatsHostMethod0 _Nonnull secondsFromGmt;
    UniffiCallbackInterfaceTokenStatsHostMethod1 _Nonnull loadWorktreeOrigins;
    UniffiCallbackInterfaceTokenStatsHostMethod2 _Nonnull recordLiveWorktrees;
} UniffiVTableCallbackInterfaceTokenStatsHost;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_CLONE_TOKENPROJECTMAPCORE
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_CLONE_TOKENPROJECTMAPCORE
uint64_t uniffi_tally_ffi_fn_clone_tokenprojectmapcore(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_FREE_TOKENPROJECTMAPCORE
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_FREE_TOKENPROJECTMAPCORE
void uniffi_tally_ffi_fn_free_tokenprojectmapcore(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_CONSTRUCTOR_TOKENPROJECTMAPCORE_BUILD
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_CONSTRUCTOR_TOKENPROJECTMAPCORE_BUILD
uint64_t uniffi_tally_ffi_fn_constructor_tokenprojectmapcore_build(RustBuffer home, uint64_t host, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_METHOD_TOKENPROJECTMAPCORE_KEY_FOR_CWD
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_METHOD_TOKENPROJECTMAPCORE_KEY_FOR_CWD
RustBuffer uniffi_tally_ffi_fn_method_tokenprojectmapcore_key_for_cwd(uint64_t ptr, RustBuffer cwd, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_CLONE_TOKENSTATSCORE
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_CLONE_TOKENSTATSCORE
uint64_t uniffi_tally_ffi_fn_clone_tokenstatscore(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_FREE_TOKENSTATSCORE
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_FREE_TOKENSTATSCORE
void uniffi_tally_ffi_fn_free_tokenstatscore(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_CONSTRUCTOR_TOKENSTATSCORE_NEW
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_CONSTRUCTOR_TOKENSTATSCORE_NEW
uint64_t uniffi_tally_ffi_fn_constructor_tokenstatscore_new(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_METHOD_TOKENSTATSCORE_SCAN
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_METHOD_TOKENSTATSCORE_SCAN
RustBuffer uniffi_tally_ffi_fn_method_tokenstatscore_scan(uint64_t ptr, RustBuffer input, uint64_t host, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_CLONE_TOKENSTATSHOST
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_CLONE_TOKENSTATSHOST
uint64_t uniffi_tally_ffi_fn_clone_tokenstatshost(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_FREE_TOKENSTATSHOST
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_FREE_TOKENSTATSHOST
void uniffi_tally_ffi_fn_free_tokenstatshost(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_INIT_CALLBACK_VTABLE_TOKENSTATSHOST
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_INIT_CALLBACK_VTABLE_TOKENSTATSHOST
void uniffi_tally_ffi_fn_init_callback_vtable_tokenstatshost(const UniffiVTableCallbackInterfaceTokenStatsHost* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_METHOD_TOKENSTATSHOST_SECONDS_FROM_GMT
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_METHOD_TOKENSTATSHOST_SECONDS_FROM_GMT
int32_t uniffi_tally_ffi_fn_method_tokenstatshost_seconds_from_gmt(uint64_t ptr, int64_t epoch_seconds, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_METHOD_TOKENSTATSHOST_LOAD_WORKTREE_ORIGINS
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_METHOD_TOKENSTATSHOST_LOAD_WORKTREE_ORIGINS
RustBuffer uniffi_tally_ffi_fn_method_tokenstatshost_load_worktree_origins(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_METHOD_TOKENSTATSHOST_RECORD_LIVE_WORKTREES
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_METHOD_TOKENSTATSHOST_RECORD_LIVE_WORKTREES
void uniffi_tally_ffi_fn_method_tokenstatshost_record_live_worktrees(uint64_t ptr, RustBuffer folds, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_FUNC_HEATMAP_CELLS
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_FUNC_HEATMAP_CELLS
RustBuffer uniffi_tally_ffi_fn_func_heatmap_cells(RustBuffer daily_totals, int64_t today, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_FUNC_HEATMAP_LEVEL
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_FUNC_HEATMAP_LEVEL
int64_t uniffi_tally_ffi_fn_func_heatmap_level(int64_t total, RustBuffer thresholds, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_FUNC_HEATMAP_THRESHOLDS
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_FUNC_HEATMAP_THRESHOLDS
RustBuffer uniffi_tally_ffi_fn_func_heatmap_thresholds(RustBuffer values, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_FUNC_HEATMAP_WEEK_COLUMNS
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_FUNC_HEATMAP_WEEK_COLUMNS
int64_t uniffi_tally_ffi_fn_func_heatmap_week_columns(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_FUNC_HEATMAP_WEEKDAY_INDEX
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_FUNC_HEATMAP_WEEKDAY_INDEX
int64_t uniffi_tally_ffi_fn_func_heatmap_weekday_index(int64_t day, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_FUNC_HEATMAP_WEEKDAYS
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_FUNC_HEATMAP_WEEKDAYS
int64_t uniffi_tally_ffi_fn_func_heatmap_weekdays(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_FUNC_HEATMAP_WINDOW_START
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_FUNC_HEATMAP_WINDOW_START
int64_t uniffi_tally_ffi_fn_func_heatmap_window_start(int64_t today, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_FUNC_HEATMAP_WINDOW_TOTAL
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_FUNC_HEATMAP_WINDOW_TOTAL
int64_t uniffi_tally_ffi_fn_func_heatmap_window_total(RustBuffer daily_totals, int64_t today, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_FUNC_TOKEN_DAILY_TOTALS
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_FUNC_TOKEN_DAILY_TOTALS
RustBuffer uniffi_tally_ffi_fn_func_token_daily_totals(RustBuffer samples, RustBuffer project, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_FUNC_TOKEN_LOCAL_DAY
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_FUNC_TOKEN_LOCAL_DAY
int64_t uniffi_tally_ffi_fn_func_token_local_day(int64_t epoch_seconds, int32_t offset_seconds, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_FUNC_TOKEN_STATS_FILE_BUCKETS
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_FUNC_TOKEN_STATS_FILE_BUCKETS
RustBuffer uniffi_tally_ffi_fn_func_token_stats_file_buckets(RustBuffer path, RustBuffer provider, uint64_t map, uint64_t host, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_FUNC_TOKEN_STATS_SOURCES
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_FUNC_TOKEN_STATS_SOURCES
RustBuffer uniffi_tally_ffi_fn_func_token_stats_sources(RustBuffer claude_homes, RustBuffer codex_homes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_FUNC_TOKEN_STATS_SUMMARIZE
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_FUNC_TOKEN_STATS_SUMMARIZE
RustBuffer uniffi_tally_ffi_fn_func_token_stats_summarize(RustBuffer samples, RustBuffer day_count, int64_t today, RustBuffer provider_order, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_FUNC_TOKEN_STATS_SWIFT_STR_PROBE
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_FN_FUNC_TOKEN_STATS_SWIFT_STR_PROBE
RustBuffer uniffi_tally_ffi_fn_func_token_stats_swift_str_probe(RustBuffer op, RustBuffer a, RustBuffer b, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUSTBUFFER_ALLOC
RustBuffer ffi_tally_ffi_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_tally_ffi_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUSTBUFFER_FREE
void ffi_tally_ffi_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUSTBUFFER_RESERVE
RustBuffer ffi_tally_ffi_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_POLL_U8
void ffi_tally_ffi_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_CANCEL_U8
void ffi_tally_ffi_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_FREE_U8
void ffi_tally_ffi_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_tally_ffi_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_POLL_I8
void ffi_tally_ffi_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_CANCEL_I8
void ffi_tally_ffi_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_FREE_I8
void ffi_tally_ffi_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_COMPLETE_I8
int8_t ffi_tally_ffi_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_POLL_U16
void ffi_tally_ffi_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_CANCEL_U16
void ffi_tally_ffi_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_FREE_U16
void ffi_tally_ffi_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_tally_ffi_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_POLL_I16
void ffi_tally_ffi_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_CANCEL_I16
void ffi_tally_ffi_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_FREE_I16
void ffi_tally_ffi_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_COMPLETE_I16
int16_t ffi_tally_ffi_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_POLL_U32
void ffi_tally_ffi_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_CANCEL_U32
void ffi_tally_ffi_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_FREE_U32
void ffi_tally_ffi_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_tally_ffi_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_POLL_I32
void ffi_tally_ffi_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_CANCEL_I32
void ffi_tally_ffi_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_FREE_I32
void ffi_tally_ffi_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_COMPLETE_I32
int32_t ffi_tally_ffi_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_POLL_U64
void ffi_tally_ffi_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_CANCEL_U64
void ffi_tally_ffi_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_FREE_U64
void ffi_tally_ffi_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_tally_ffi_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_POLL_I64
void ffi_tally_ffi_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_CANCEL_I64
void ffi_tally_ffi_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_FREE_I64
void ffi_tally_ffi_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_COMPLETE_I64
int64_t ffi_tally_ffi_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_POLL_F32
void ffi_tally_ffi_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_CANCEL_F32
void ffi_tally_ffi_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_FREE_F32
void ffi_tally_ffi_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_COMPLETE_F32
float ffi_tally_ffi_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_POLL_F64
void ffi_tally_ffi_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_CANCEL_F64
void ffi_tally_ffi_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_FREE_F64
void ffi_tally_ffi_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_COMPLETE_F64
double ffi_tally_ffi_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_tally_ffi_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_tally_ffi_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_tally_ffi_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_tally_ffi_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_POLL_VOID
void ffi_tally_ffi_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_CANCEL_VOID
void ffi_tally_ffi_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_FREE_VOID
void ffi_tally_ffi_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_RUST_FUTURE_COMPLETE_VOID
void ffi_tally_ffi_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_FUNC_HEATMAP_CELLS
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_FUNC_HEATMAP_CELLS
uint16_t uniffi_tally_ffi_checksum_func_heatmap_cells(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_FUNC_HEATMAP_LEVEL
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_FUNC_HEATMAP_LEVEL
uint16_t uniffi_tally_ffi_checksum_func_heatmap_level(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_FUNC_HEATMAP_THRESHOLDS
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_FUNC_HEATMAP_THRESHOLDS
uint16_t uniffi_tally_ffi_checksum_func_heatmap_thresholds(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_FUNC_HEATMAP_WEEK_COLUMNS
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_FUNC_HEATMAP_WEEK_COLUMNS
uint16_t uniffi_tally_ffi_checksum_func_heatmap_week_columns(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_FUNC_HEATMAP_WEEKDAY_INDEX
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_FUNC_HEATMAP_WEEKDAY_INDEX
uint16_t uniffi_tally_ffi_checksum_func_heatmap_weekday_index(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_FUNC_HEATMAP_WEEKDAYS
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_FUNC_HEATMAP_WEEKDAYS
uint16_t uniffi_tally_ffi_checksum_func_heatmap_weekdays(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_FUNC_HEATMAP_WINDOW_START
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_FUNC_HEATMAP_WINDOW_START
uint16_t uniffi_tally_ffi_checksum_func_heatmap_window_start(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_FUNC_HEATMAP_WINDOW_TOTAL
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_FUNC_HEATMAP_WINDOW_TOTAL
uint16_t uniffi_tally_ffi_checksum_func_heatmap_window_total(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_FUNC_TOKEN_DAILY_TOTALS
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_FUNC_TOKEN_DAILY_TOTALS
uint16_t uniffi_tally_ffi_checksum_func_token_daily_totals(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_FUNC_TOKEN_LOCAL_DAY
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_FUNC_TOKEN_LOCAL_DAY
uint16_t uniffi_tally_ffi_checksum_func_token_local_day(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_FUNC_TOKEN_STATS_FILE_BUCKETS
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_FUNC_TOKEN_STATS_FILE_BUCKETS
uint16_t uniffi_tally_ffi_checksum_func_token_stats_file_buckets(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_FUNC_TOKEN_STATS_SOURCES
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_FUNC_TOKEN_STATS_SOURCES
uint16_t uniffi_tally_ffi_checksum_func_token_stats_sources(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_FUNC_TOKEN_STATS_SUMMARIZE
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_FUNC_TOKEN_STATS_SUMMARIZE
uint16_t uniffi_tally_ffi_checksum_func_token_stats_summarize(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_FUNC_TOKEN_STATS_SWIFT_STR_PROBE
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_FUNC_TOKEN_STATS_SWIFT_STR_PROBE
uint16_t uniffi_tally_ffi_checksum_func_token_stats_swift_str_probe(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_METHOD_TOKENPROJECTMAPCORE_KEY_FOR_CWD
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_METHOD_TOKENPROJECTMAPCORE_KEY_FOR_CWD
uint16_t uniffi_tally_ffi_checksum_method_tokenprojectmapcore_key_for_cwd(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_METHOD_TOKENSTATSCORE_SCAN
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_METHOD_TOKENSTATSCORE_SCAN
uint16_t uniffi_tally_ffi_checksum_method_tokenstatscore_scan(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_METHOD_TOKENSTATSHOST_SECONDS_FROM_GMT
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_METHOD_TOKENSTATSHOST_SECONDS_FROM_GMT
uint16_t uniffi_tally_ffi_checksum_method_tokenstatshost_seconds_from_gmt(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_METHOD_TOKENSTATSHOST_LOAD_WORKTREE_ORIGINS
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_METHOD_TOKENSTATSHOST_LOAD_WORKTREE_ORIGINS
uint16_t uniffi_tally_ffi_checksum_method_tokenstatshost_load_worktree_origins(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_METHOD_TOKENSTATSHOST_RECORD_LIVE_WORKTREES
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_METHOD_TOKENSTATSHOST_RECORD_LIVE_WORKTREES
uint16_t uniffi_tally_ffi_checksum_method_tokenstatshost_record_live_worktrees(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_CONSTRUCTOR_TOKENPROJECTMAPCORE_BUILD
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_CONSTRUCTOR_TOKENPROJECTMAPCORE_BUILD
uint16_t uniffi_tally_ffi_checksum_constructor_tokenprojectmapcore_build(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_CONSTRUCTOR_TOKENSTATSCORE_NEW
#define UNIFFI_FFIDEF_UNIFFI_TALLY_FFI_CHECKSUM_CONSTRUCTOR_TOKENSTATSCORE_NEW
uint16_t uniffi_tally_ffi_checksum_constructor_tokenstatscore_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TALLY_FFI_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_TALLY_FFI_UNIFFI_CONTRACT_VERSION
uint32_t ffi_tally_ffi_uniffi_contract_version(void
    
);
#endif

